### PR TITLE
Add route searching

### PR DESCRIPTION
**Pull request by mparrett**
# Summary

Hacked this together so I could inspect groups of climbs in the clustering side-quest.

It's not pretty, but it works. Someone with more experience could probably repair my damage.

Known issues:
- interferes with copy/paste sometimes

### CODE REVIEW

**Comment by mparrett** [comment]
cc: @rparrett

**Comment by rparrett** [comment]
Ooh, cool. Seems useful. I can help clean this up at some point, but notes for later:

- Key handling can be simplified greatly by reading `KeyboardInput` events. You can get a `str` for the key from `logical_key`. ([taipo](https://github.com/rparrett/taipo/blob/main/src/typing.rs#L403), [official example](https://github.com/bevyengine/bevy/blob/latest/examples/input/text_input.rs#L171)).
  [bevy_simple_text_input](https://github.com/rparrett/bevy_simple_text_input) is also an option, but is probably overkill.
- No way to get a keyboard on native mobile builds at the moment. Should make sure this isn't intrusive there.
- I wonder why we made the board transparent.

**Comment by mparrett** [comment]
Awesome, this is quite helpful! I'll let you know if I am able to update it.

Regarding the transparent board, I wanted a way to enhance the "contrast" as I was viewing a bunch of climbs in a row. I also tried some lights for the LEDs but that failed.

**Comment by rparrett** [comment]
Cleaned this up a bit and documented the copy/paste issue in #2.

**Pull request merged**
